const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const assert = require('node:assert/strict')
;(async () => {
  const browser = await chromium.launch({headless:true})
  const page = await browser.newPage({viewport:{width:1440,height:960}})
  const errors = []
  page.on('pageerror', error => { errors.push(error.message); console.error(error.stack) })
  await page.goto('http://127.0.0.1:5175/novel-preview.html')
  await page.locator('.desk').waitFor()
  await page.screenshot({path:'novel-desktop.png'})
  await page.locator('#novelChapterContent').fill('第一行正文\n\n第二行正文，保存后不应丢失。')
  await page.waitForTimeout(700)
  assert.equal(await page.evaluate(()=>window.previewWorkspace.novels[0].chapters[0].content), '第一行正文\n\n第二行正文，保存后不应丢失。')
  await page.locator('[data-act="chapter-inline"][data-index="1"]').click()
  await page.locator('[data-act="chapter-inline"][data-index="0"]').click()
  assert.match(await page.locator('#novelChapterContent').inputValue(),/第二行正文/)
  await page.locator('.desk-status [data-act="append"]').click()
  assert.equal(await page.locator('#novelChapterContent').inputValue(),'')
  assert.equal(await page.evaluate(()=>window.previewWorkspace.novels[0].chapters.length),9)
  await page.locator('#deskFocus').click()
  assert.equal(await page.locator('.desk-sidebar').isVisible(),false)
  await page.locator('#deskFocus').click()
  await page.locator('[data-act="chapter-inline"][data-index="1"]').click()
  await page.locator('[data-act="immersive"]').click()
  await page.screenshot({path:'novel-reader.png'})
  const first = await page.locator('output').innerText()
  await page.locator('[data-next]').click()
  assert.notEqual(await page.locator('output').innerText(),first)
  await page.locator('[data-display]').click()
  await page.locator('[data-theme="night"]').click()
  await page.locator('[data-mode]').selectOption('scroll')
  await page.screenshot({path:'novel-reader-night.png'})
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('.reading-room').count(),0)
  await page.setViewportSize({width:390,height:844})
  await page.reload()
  await page.locator('.desk').waitFor()
  assert.equal(await page.locator('.desk-sidebar').isVisible(),false)
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
  await page.screenshot({path:'novel-mobile.png'})
  await page.locator('[data-act="immersive"]').click()
  await page.screenshot({path:'novel-reader-mobile.png'})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
  await page.keyboard.press('Escape')
  await page.locator('#novelBack').click()
  await page.screenshot({path:'novel-library-mobile.png'})
  assert.deepEqual(errors,[])
  await page.setViewportSize({width:1440,height:960})
  await page.screenshot({path:'novel-library.png'})
  await page.reload()
  await page.locator('[data-index="3"]').click()
  await page.locator('[data-sidebar-delete="chapter-0"]').click()
  await page.locator('#confirmCancelBtn').click()
  assert.equal(await page.evaluate(()=>window.previewWorkspace.novels[0].chapters.length),8)
  await page.evaluate(() => {
    window.previewWorkspace.novels[0].outline.chapterSummaries = [{chapterIndex:0,title:'remove',summary:'remove'},{chapterIndex:3,title:'keep',summary:'keep'}]
  })
  await page.locator('[data-sidebar-delete="chapter-0"]').click()
  await page.locator('#confirmOkBtn').click()
  await page.waitForFunction(()=>window.previewWorkspace.novels[0].chapters.length===7)
  assert.equal(await page.locator('#novelChapterTitle').innerText(),'没有寄出的明信片')
  assert.equal(await page.evaluate(()=>window.previewWorkspace.novels[0].outline.chapterSummaries[0].chapterIndex),2)
  await page.locator('[data-sidebar-delete="chapter-3"]').click()
  await page.locator('#confirmOkBtn').click()
  await page.waitForFunction(()=>window.previewWorkspace.novels[0].chapters.length===6)
  assert.equal(await page.locator('#novelChapterTitle').innerText(),'沿海公路')
  await page.locator('#novelChapterFilter').fill('沿海')
  assert.equal(await page.locator('.desk-chapter-row:visible').count(),1)
  assert.equal(await page.locator('[data-sidebar-delete]:visible').count(),1)
  await page.locator('#novelChapterFilter').fill('')
  await page.screenshot({path:'novel-sidebar-delete.png'})
  while (await page.locator('[data-sidebar-delete]').count()) {
    const count = await page.locator('[data-sidebar-delete]').count()
    await page.locator('[data-sidebar-delete]').first().click()
    await page.locator('#confirmOkBtn').click()
    await page.waitForFunction(expected=>window.previewWorkspace.novels[0].chapters.length===expected,count-1)
  }
  assert.equal(await page.locator('[data-act="first"]').isVisible(),true)
  assert.deepEqual(errors,[])
  console.log('PASS: sidebar delete cancellation, preceding/current/last chapter deletion, memory renumbering, filtered delete buttons.')
  console.log('PASS: editing, persistence, chapter navigation, blank chapter, focus, pagination, themes, scroll mode, Escape, desktop and mobile.')
  await browser.close()
})().catch(error=>{console.error(error);process.exit(1)})
